### ISSUE TITLE
Portfolio broken

### ISSUE THREAD

**Issue by vinylcut** [mikaelstaer/The-Secretary#11]
A client's portfolio site was not working, so we updated the PHP and to the most recent version of Secretary, but now the main portfolio page with thumbnails won't load.

This is how the portfolio/home page should look:
![screenshot](https://user-images.githubusercontent.com/97646279/149249209-9898d8b4-97c8-430e-bd7b-4af4d3d1a30b.jpeg)

My developer was trying to change a line of code in the template, but only one thumbnail loads (lol):
http://davidwongcreative.com/

Any help appreciated! Thanks

**Comment by mikaelstaer** [comment]
Which version of PHP are you running now?

There may be some compatibility issues with the absolute latest version of PHP and Secretary.

**Comment by mikaelstaer** [comment]
Actually, I think your developer made an error in the template!
![CleanShot 2022-01-13 at 09 54 28@2x](https://user-images.githubusercontent.com/726556/149353287-769fe78d-8ab8-4643-95a1-5df3342442a4.png)

Looks like some broken HTML.

As a result, there's actually only the one project on the page - nothing else is in there.

**Comment by mikaelstaer** [comment]
Solved - issues due to custom theme functions.
